### ISSUE TITLE
Delay scanning battlefield on slower machines

### ISSUE THREAD

**Issue by giraffesyo** [invokehub/invokestatic#108]
For slower machines or VMs add detection for when clash of clans is still searching for a base to attack. (White clouds). If this is not feasible introduce a slider in advanced settings which will allow for users to predetermine time to wait. 

![image](https://cloud.githubusercontent.com/assets/10459772/5933347/c255d588-a684-11e4-92c6-f250e65f28ca.png)

**Comment by invokehub** [comment]
Done.
