### ISSUE TITLE
12.8, Bot aborts the attack after dropping 60 barbs

### ISSUE THREAD

**Issue by Loomies** [invokehub/invokestatic#114]
It happened with both my CoC accounts(Vmware and regular windows). I did a fresh installed after it happened and it still does it. This error showed up 2 times in the log after it dropped the barbs. It never showed up again but the problem stil continues(it leaves after dropping a few dozen barbs 5 seconds into a fight)

I never have trophy drop enable.

The first few times it did this error when it was suppose to drop the archers(it spammed this and then it suddenly leaves the match)

http://community.invokestatic.com/uploads/default/199/13a8c26445090ccf.jpg
Now this happens after fresh install

http://community.invokestatic.com/uploads/default/200/f3811926da7209b4.jpg

http://community.invokestatic.com/uploads/default/201/76c116877524cd9b.jpg

Cant rollback to previous version atm. 
Regular:
Windows 8, Java 8

Vmware:
Windows 7, java 8

**Comment by invokehub** [comment]
Your mouse speed is too low (too fast).  Raise the delay (slower).

**Comment by Loomies** [comment]
Close this please. sorry invoke, i feel like an idiot now

**Comment by invokehub** [comment]
@Loomies did you have it at 0? lol
