### ISSUE TITLE
12.8 BUGGED?

### ISSUE THREAD

**Issue by GEKTHEBOSS** [invokehub/invokestatic#115]
I just putted 12.8 on night, then 9 hour after i woke up and i was waiting to see my 7mill storages buuut my gold was 280, all collectors was uncollected, i was 1100 cups from 1400. So i watched attacks and the bot found nice bases, but placed some barbs and ended the battles!

**Comment by giraffesyo** [comment]
put your mouse speed up to 1

**Comment by GEKTHEBOSS** [comment]
Control panel ot cocabot?

**Comment by giraffesyo** [comment]
in cocabot advanced settings

**Comment by GEKTHEBOSS** [comment]
still didn't fix.. i get out of gold!

i tried also uncheck "collector base" but nothing!

+ another thing till 12.6 was working perfect, from 12.7 bubble check give 1 instead 2 so bot waste time on barrack ! my base still same

**Comment by giraffesyo** [comment]
if you dont have 100k gold you cant run the bot.
