### ISSUE TITLE
Upgrade intelligent raiding

### ISSUE THREAD

**Issue by invokehub** [invokehub/invokestatic#28]
Have intelligent raiding detect between full storages, mines, or both and attack accordingly.  At the moment it focuses on a balance of storages and mines when raiding.

**Comment by giraffesyo** [comment]
![image](https://cloud.githubusercontent.com/assets/10459772/5691878/9c1083d2-98a1-11e4-9da4-c91c85ced1ed.png)

**Comment by invokehub** [comment]
Done.
