### ISSUE TITLE
Interactive Mode - Once finds a base pause and prompt the user with a window showing North/South/East/West allowing them to pick which side to attack from (Dont play the game, play the bot)

### ISSUE THREAD

**Issue by mnestroy** [invokehub/invokestatic#47]

**Comment by giraffesyo** [comment]
Not sure of the demand of a feature like this, seems similar to Xmod. If we look into a feature like this I'd say definitely need an option to automatically deploy as normal if no options selected within a certain time.

**Comment by bosslaw** [comment]
A bot is designed to remove manual interaction. This is not a good suggestion I guess.
