### ISSUE TITLE
In Beta 10 Pause button does not function, as expected or imediately.

### ISSUE THREAD

**Issue by mnestroy** [invokehub/invokestatic#54]
It might not be a full bug, but the pause does not immediately pause, After pressing pause depending on what action/procedure is being performed/ran there is a delay before pause takes effect.  

I will continue to test to replicate. In below screen shot I had hit pause and it took approximately 10 seconds before there was no further updates in the black window or actions taken.

![ss 2015-01-09 at 01 01 43](https://cloud.githubusercontent.com/assets/10452210/5685454/e297f62a-97ff-11e4-8beb-eb1b9882e600.jpg)

**Comment by invokehub** [comment]
This is the intended functionality.
