### ISSUE TITLE
Enhance pause to be immediate

### ISSUE THREAD

**Issue by giraffesyo** [invokehub/invokestatic#58]
Enhance pause function to be immediately after the pause button is pushed rather than after current action is finished. Integrate same function (temporary pause) when bot detects another device connecting. This will fix it so arguing between device and blue stacks won't happen. Taking this further make it a setting in the bots advanced settings on how long it Should wait before it resumes botting when another device connects.

**Comment by giraffesyo** [comment]
I understand the similarities to #14 and #25

**Comment by invokehub** [comment]
Unfortunately, this is not possible. :(
