### ISSUE TITLE
Investigate gui scaling issue

### ISSUE THREAD

**Issue by giraffesyo** [invokehub/invokestatic#59]
via http://community.invokestatic.com/t/scaling-issue-with-4k/278

At higher resolutions GUI doesn't display properly

![image](https://cloud.githubusercontent.com/assets/10459772/5694018/bef2db52-9900-11e4-9385-491c12af4f9d.png)

**Comment by invokehub** [comment]
This is caused by java itself, try upgrading to Java 8 and see if that fixes 4k issues.

**Comment by spsp31** [comment]
Will update and let you know, thanks

**Comment by invokehub** [comment]
Very odd...  The GUI lets java itself handle the size...

**Comment by giraffesyo** [comment]
Now that the bot is being compiled in Java 8 is this issue still happening?

**Comment by spsp31** [comment]
Issue is not fixed
![lkb30h1](https://cloud.githubusercontent.com/assets/9311382/5913973/c65e0524-a5b2-11e4-853a-d7129c01ebfb.jpg)

**Comment by giraffesyo** [comment]
https://github.com/invokehub/invokestatic/issues/120

Bot now allows for resizing.
