### ISSUE TITLE
Make GUI Not Close/Exit when you Press stop - Add Seperate Button that says Exit

### ISSUE THREAD

**Issue by mnestroy** [invokehub/invokestatic#65]
Add button that says exit - Exits the bot
Stop button = brings you back to main settings page so you can change values instead of being forced to re-launch program and re-enter all settings

**Comment by giraffesyo** [comment]
+1

**Comment by invokehub** [comment]
I *already* denied this, but I **will** implement saving and auto loading of settings.  See issue #7.
