### ISSUE TITLE
Training another troop on accident

### ISSUE THREAD

**Issue by DehGhetto** [invokehub/invokestatic#68]
Usually I let the bot run for 2 or 3 hours before coming back to check.  When I come back it is topping off the barracks and I see that somehow 2 giants have gotten in my barbarian barrack.  I always make sure my barracks are cleaned when I start the bot.  Not sure if this is a common issue with others or not.  Its happened twice now.

**Comment by dracco1993** [comment]
This appears to be the same issue as #11.

**Comment by invokehub** [comment]
Same as #11.
