### ISSUE TITLE
Troop donation is using the wrong field when "Multiplayer auto raider" is set

### ISSUE THREAD

**Issue by dracco1993** [invokehub/invokestatic#78]
No matter what is set here:
![](http://puu.sh/eBJd9/ebdbda0afb.png)

If "Multiplayer auto raider" is set:
![](http://puu.sh/eBJaV/c1151a0e7b.png)

Whatever is set here is what is actually donated:
![](http://puu.sh/eBID5/5217ce7b14.png)

**Comment by invokehub** [comment]
Fixed.

**Comment by dracco1993** [comment]
Sweet.
