### ISSUE TITLE
Bases being skipped that should've been attacked.

### ISSUE THREAD

**Issue by giraffesyo** [invokehub/invokestatic#87]
Bot is skipping bases with correct amount of resources with ALL selected.

![image](https://cloud.githubusercontent.com/assets/10459772/5795066/7f36e8e4-9f4c-11e4-89e2-7f55c90ce34b.png)

This base had 1k DE in addition to the 227k gold and 415k elixer it had. 

![image](https://cloud.githubusercontent.com/assets/10459772/5795059/64f9d220-9f4c-11e4-8469-e3050d21456a.png)

**Comment by giraffesyo** [comment]
Also happens with set to 0 

![image](https://cloud.githubusercontent.com/assets/10459772/5795084/ef8b00bc-9f4c-11e4-9e6e-61f27305ac41.png)

**Comment by dracco1993** [comment]
Yeah, I thought I've seen this before, but I wasn't sure.

**Comment by invokehub** [comment]
Added some debug, please present it in the next beta if/when it happens again.
