### ISSUE TITLE
Barracks check failing after one attack

### ISSUE THREAD

**Issue by giraffesyo** [invokehub/invokestatic#89]
After one attack bot fails to find barracks and times out then continues working for another attack, rinse, repeat.

![image](https://cloud.githubusercontent.com/assets/10459772/5798096/b7caaa46-9f89-11e4-9ea8-8d6975ad3b93.png)

![image](https://cloud.githubusercontent.com/assets/10459772/5798097/bcb10fe6-9f89-11e4-81fe-7c8eb5b83a66.png)

**Comment by invokehub** [comment]
Fixed.
