### ISSUE TITLE
[BUG?] Heroes Ability

### ISSUE THREAD

**Issue by GEKTHEBOSS** [invokehub/invokestatic#93]
heros ability is sometimes triggered ?

Activating troop index 2 and index 3.

**Comment by giraffesyo** [comment]
Do you mean your hero is dying before activating the ability?

**Comment by GEKTHEBOSS** [comment]
Yes! I mean it could be like enable the ability when it have 50% life or something like that

**Comment by invokehub** [comment]
Fixed.
