### ISSUE TITLE
Failed -- waiting for timeout so we can start fresh (UNKNOWN STATE).

### ISSUE THREAD

**Issue by ryanjh5521** [invokehub/invokestatic#95]
I get this issue only when I am not using Remote Desktop on my VPS. Possibly something to do with nothing viewing the game?

Starting raiding sequence
Checking for resources.
No resources found.
Checking barracks fill...
Finding distinguishing window...
Found the window on the '2' try.
Checking barracks 1.
Failed to fill barracks.
Failed to open barracks.
Checking barracks fill...
Finding distinguishing window...
Found the window on the '4' try.
Checking barracks 1.
Failed to fill barracks.
Failed to open barracks.
Checking barracks fill...
Finding distinguishing window...
Found the window on the '2' try.
Checking barracks 1.
Failed to fill barracks.
Failed to open barracks.
Checking for resources.
No resources found.
Checking barracks fill...
Finding distinguishing window...
Found the window on the '4' try.
Checking barracks 1.
Failed to fill barracks.
Failed to open barracks.
Checking barracks fill...
Finding distinguishing window...
Found the window on the '4' try.
Checking barracks 1.
Failed to fill barracks.
Failed to open barracks.
Failed 5 times. Setting failed state to 'true'.
Failed -- waiting for timeout so we can start fresh (UNKNOWN STATE).

**Comment by invokehub** [comment]
Yes the game must be being rendered.

**Comment by ryanjh5521** [comment]
Is there a workaround for this?

**Comment by invokehub** [comment]
Unless if you have knowledge of windows api, I'm afraid not.

**Comment by ryanjh5521** [comment]
Whatever the issue was it stopped when running the bot as administrator

**Comment by invokehub** [comment]
Cool!
